/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_willian_garcia_miguel_julio.views;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static lab_willian_garcia_miguel_julio.controls.Lab_Willian_Garcia_Miguel_Julio.LaPros;
import lab_willian_garcia_miguel_julio.models.Gerente;
import lab_willian_garcia_miguel_julio.models.Mesero;

/**
 *
 * @author Administrador
 */
public class WGerente extends javax.swing.JFrame {

    /**
     * Creates new form WGerente
     */
    private static Gerente gr=new Gerente();
    public WGerente() {
        initComponents();
        int x=LaPros.getNumerom();
        jComboBox1.removeAllItems();
        for (int i=1; i<=x; i++) {
            jComboBox1.addItem(i+"");
        }
        this.setSize(355, 283);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(251, 248, 198));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Resumen detallado");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Resumen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(51, 52, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(70, 10, 205, 91);

        jPanel2.setBackground(new java.awt.Color(251, 248, 198));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("<html>Total<br/>Ventas</html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<html>Plato<br/>Mas vendido</html>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<html>Mesero con<br/>mayor gestion</html>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("<html>5 categorias<br/>Mas vendidas</html>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 120, 298, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-510, 0, 890, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String msg=catMas(),out="";
            if(msg.equals("")){
                JOptionPane.showMessageDialog(null, "No se ha vendido ningun plato");
            }else{
                StringTokenizer st= new StringTokenizer(msg,";");
                if(st.countTokens()<=10){
                    while(st.hasMoreTokens()){
                        out+=st.nextToken()+"->"+st.nextToken()+"\n";
                    }
                    JOptionPane.showMessageDialog(null,"Las categorias con mas ventas son:\n"+out);
                }else{
                    st= new StringTokenizer(msg,";");
                    String max1="",max2="",max3="",max4="",max5="";
                    int  in1=0,in2=0,in3=0,in4=0,in5=0;
                    while(st.hasMoreTokens()){
                        String n=st.nextToken();
                        int nt=Integer.parseInt(st.nextToken());
                        if(nt>in5){
                            max1=max2;
                            max2=max3;
                            max3=max4;
                            max4=max5;
                            max5=n;
                            in1=in2;
                            in2=in3;
                            in3=in4;
                            in4=in5;
                            in5=nt;
                        }else if(nt>in4){
                            max1=max2;
                            max2=max3;
                            max3=max4;
                            max4=n;
                            in1=in2;
                            in2=in3;
                            in3=in4;
                            in4=nt;
                        }else if(nt>in3){
                            max1=max2;
                            max2=max3;
                            max3=n;
                            in1=in2;
                            in2=in3;
                            in3=nt;
                        }else if(nt>in2){
                            max1=max2;
                            max2=n;
                            in1=in2;
                            in2=nt;
                        }else if(nt>in1){
                            max1=n;
                            in1=nt;
                        }
                    }
                    out=max5+"->"+in5+"\n"+max4+"->"+in4+"\n"+max3+"->"+in3+"\n"+max2+"->"+in2+"\n"+max1+"->"+in1;
                    JOptionPane.showMessageDialog(null,"Las 5 categorias con mas ventas son:\n"+out);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(WGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(LaPros.getEmpleados()!=null){
            Mesero temp=gr.mgestion();
            if(temp.getMgestionadas()!=0)JOptionPane.showMessageDialog(null,"El mesero con mejor gestion es :\nNombre:"+temp.getNombre()+"\nCC:"+temp.getCc()+"\nCon "+temp.getMgestionadas()+" gestiones");
            else JOptionPane.showMessageDialog(null,"No se ha gestionado ninguna mesa");
        }else{
            JOptionPane.showMessageDialog(null,"No se ha registrado ningun mesero");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String msg=plMas();
            if(msg.equals("")){
                JOptionPane.showMessageDialog(null, "No se ha vendido ningun plato");
            }else{
                StringTokenizer st= new StringTokenizer(msg,";");
                int max=0;
                String nombre="";
                while(st.hasMoreTokens()){
                    String tem=st.nextToken(),can=st.nextToken();
                    if(max<Integer.parseInt(can)){
                        nombre=tem;
                        max=Integer.parseInt(can);
                    }
                }
                JOptionPane.showMessageDialog(null, "El plato mas vendido es\n"+ nombre +"\ncon "+max+" ventas");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(WGerente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(WGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            JOptionPane.showMessageDialog(null,"Las ventas totales son \n"+gr.totalVentas());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(WGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String mesa=jComboBox1.getSelectedItem().toString();
            W2Gerente v1= new W2Gerente(this,mesa);
            v1.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(WGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    private String catMas() throws FileNotFoundException, IOException{
        BufferedReader br1 = new BufferedReader(new FileReader("Archivos\\Consolidados\\Categorias.txt"));
    String linea1 = br1.readLine(),registro="";
    while(linea1!=null){
        StringTokenizer st= new StringTokenizer(linea1,";");
        String nombre=st.nextToken();
        int cant=Integer.parseInt(st.nextToken());
            if(ver(nombre,registro)){
                BufferedReader br2 = new BufferedReader(new FileReader("Archivos\\Consolidados\\Categorias.txt"));
                String linea2 = br2.readLine();
                int c=0;
                while(linea2!=null){
                StringTokenizer st1= new StringTokenizer(linea2,";");
                String n=st1.nextToken(),can=st1.nextToken();
                    if(nombre.equals(n)){
                        c+=Integer.parseInt(can);
                    }
                    linea2=br2.readLine();
                }
                registro+=nombre+";"+c+";";
                br2.close();
            }
            linea1=br1.readLine();
        }
    br1.close();
        System.out.println(registro);
    return registro;
    }
    private String plMas() throws FileNotFoundException, IOException{
    BufferedReader br1 = new BufferedReader(new FileReader("Archivos\\Consolidados\\Platos.txt"));
    String linea1 = br1.readLine(),registro="";
    while(linea1!=null){
        StringTokenizer st= new StringTokenizer(linea1,";");
        String nombre=st.nextToken();
        int cant=Integer.parseInt(st.nextToken());
            if(ver(nombre,registro)){
                BufferedReader br2 = new BufferedReader(new FileReader("Archivos\\Consolidados\\Platos.txt"));
                String linea2 = br2.readLine();
                int c=0;
                while(linea2!=null){
                StringTokenizer st1= new StringTokenizer(linea2,";");
                String n=st1.nextToken(),can=st1.nextToken();
                    if(nombre.equals(n)){
                        c+=Integer.parseInt(can);
                    }
                    linea2=br2.readLine();
                }
                registro+=nombre+";"+c+";";
                br2.close();
            }
            linea1=br1.readLine();
        }
    br1.close();
    return registro;
    }
    private boolean ver(String name, String registros){
        StringTokenizer st= new StringTokenizer(registros,";");
        while(st.hasMoreTokens()){
            if(name.equals(st.nextToken()))return false;
            st.nextToken();
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
